name: Tuc_Comercial
description: "Una guía comercial mejorada con soporte para múltiples ciudades y búsqueda por cercanía."

publish_to: 'none'

version: 1.0.0+14

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  card_swiper: ^3.0.1
  url_launcher: ^6.2.5
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  image_picker: ^1.2.0
  share_plus: ^7.2.0
  speech_to_text: ^7.0.0
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_foreground.png" # Ruta a la imagen del primer plano
  adaptive_icon_background: "#FFD700"     # Código hexadecimal de tu amarillo
  adaptive_icon_foreground: "assets/logo_foreground.png" # Usamos la misma imagen
  min_sdk_android: 23 # Para Android, la versión mínima
flutter:
  uses-material-design: true

  assets:
    - assets/logo_foreground.png
    # Si también usas la carpeta "fonts" que se ve en tu proyecto:
    - assets/fonts/


  # La indentación (espacios) debe ser EXACTAMENTE así
  fonts:
    - family: Inter
      fonts: # <-- Esta es la clave que faltaba
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700